version: '3.9'

services:
  load_balancer:
    image: loadbalancer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    image: server
    environment:
      - APP=server1
    ports:
      - "5001:5000"

  server2:
    image: server
    environment:
      - APP=server2
    ports:
      - "5002:5000"

  server3:
    image: server
    environment:
      - APP=server3
    ports:
      - "5003:5000"