version: '5.0.3'

services:
  app:
    build:
      context: .
    ports:
      - "5000"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"