services:
  load_balancer:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: load-balancer
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_ID=1
    container_name: server1
    ports:
      - "5001:5001"

  server2:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_ID=2
    container_name: server2
    ports:
      - "5002:5002"

  server3:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_ID=3
    container_name: server3
    ports:
      - "5003:5003"