services:
  server1:
    container_name: server1
    build: ./server1
    ports:
      - "5001:5000"
  server2:
    container_name: server2
    build: ./server2
    ports:
      - "5002:5000"
  server3:
    container_name: server3
    build: ./server3
    ports:
      - "5003:5000"
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - server1
      - server2
      - server3